module.exports = function (grunt) {
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    assets:'src/assets',
    js:'<%=assets%>/js',
    jsmin:'<%=js%>/min',
    css:'<%=assets%>/css',
    sassPath:'<%=css%>/sass',
    clean:{
      js:{
        src:'<%=jsmin%>'
      },
      css:{
        src:['<%=css%>/*.css','<%=css%>/*.map']
      }
    },
    sass:{
      build:{
        files:[
          {
            expand:true,
            cwd:'<%=sassPath%>',
            src:['*.scss'],
            dest:'<%=css%>',
            ext:'.css'
          }
        ]
      }
    },
    watch:{
      sass:{
        files:['<%=sassPath%>/*.scss','<%=sassPath%>/**/*.scss'],
        tasks:['sass']
      }
    },
    uglify: {
      options: {
        banner: '/*! <%=pkg.name%> <%=grunt.template.today("yyyy-mm-dd") %>*/'
      },
      build:{
        files:[
          {
            expand:true,
            cwd:'<%=js%>',
            src:'*.js',
            dest:'dist/assets/js'
          }
        ]
      }
    },
    cssmin:{
      build:{
        files:[
          {
            expand:true,
            cwd:'<%=css%>',
            src:'*.css',
            dest:'dist/assets/css'
          }
        ]
      }
    },
    copy:{
      file:{
        expand:true,
        cwd:"src",
        src:["**",'!assets/css/**','!assets/js/**'],
        dest:"dist/"
      }
    }
  });

  grunt.loadNpmTasks('grunt-contrib-uglify');
  grunt.loadNpmTasks('grunt-contrib-clean');
  grunt.loadNpmTasks('grunt-contrib-sass');
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-contrib-cssmin');
  grunt.loadNpmTasks('grunt-contrib-copy');

  grunt.registerTask('default',['watch']);
  grunt.registerTask('build',['uglify','cssmin','copy']);
};
